In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('./GroceryStoreDataSet.csv',names=['products'],header=None)

In [4]:
data

                          products
0               MILK,BREAD,BISCUIT
1    BREAD,MILK,BISCUIT,CORNFLAKES
2              BREAD,TEA,BOURNVITA
3             JAM,MAGGI,BREAD,MILK
4                MAGGI,TEA,BISCUIT
5              BREAD,TEA,BOURNVITA
6             MAGGI,TEA,CORNFLAKES
7          MAGGI,BREAD,TEA,BISCUIT
8              JAM,MAGGI,BREAD,TEA
9                       BREAD,MILK
10  COFFEE,COCK,BISCUIT,CORNFLAKES
11  COFFEE,COCK,BISCUIT,CORNFLAKES
12          COFFEE,SUGER,BOURNVITA
13               BREAD,COFFEE,COCK
14             BREAD,SUGER,BISCUIT
15         COFFEE,SUGER,CORNFLAKES
16           BREAD,SUGER,BOURNVITA
17              BREAD,COFFEE,SUGER
18              BREAD,COFFEE,SUGER
19      TEA,MILK,COFFEE,CORNFLAKES

In [5]:
data.columns

Index(['products'], dtype='object')

In [6]:
data.values

array([['MILK,BREAD,BISCUIT'],
       ['BREAD,MILK,BISCUIT,CORNFLAKES'],
       ['BREAD,TEA,BOURNVITA'],
       ['JAM,MAGGI,BREAD,MILK'],
       ['MAGGI,TEA,BISCUIT'],
       ['BREAD,TEA,BOURNVITA'],
       ['MAGGI,TEA,CORNFLAKES'],
       ['MAGGI,BREAD,TEA,BISCUIT'],
       ['JAM,MAGGI,BREAD,TEA'],
       ['BREAD,MILK'],
       ['COFFEE,COCK,BISCUIT,CORNFLAKES'],
       ['COFFEE,COCK,BISCUIT,CORNFLAKES'],
       ['COFFEE,SUGER,BOURNVITA'],
       ['BREAD,COFFEE,COCK'],
       ['BREAD,SUGER,BISCUIT'],
       ['COFFEE,SUGER,CORNFLAKES'],
       ['BREAD,SUGER,BOURNVITA'],
       ['BREAD,COFFEE,SUGER'],
       ['BREAD,COFFEE,SUGER'],
       ['TEA,MILK,COFFEE,CORNFLAKES']], dtype=object)

In [11]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
transformed_data = list(data["products"].apply(lambda x:x.split(',')))
te_data = te.fit(transformed_data).transform(transformed_data)
df = pd.DataFrame(te_data,columns=te.columns_)
df

,BISCUIT,BOURNVITA,BREAD,COCK,COFFEE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,True,False,True,False,False,False,False,False,True,False,False
1,True,False,True,False,False,True,False,False,True,False,False
2,False,True,True,False,False,False,False,False,False,False,True
3,False,False,True,False,False,False,True,True,True,False,False
4,True,False,False,False,False,False,False,True,False,False,True
5,False,True,True,False,False,False,False,False,False,False,True
6,False,False,False,False,False,True,False,True,False,False,True
7,True,False,True,False,False,False,False,True,False,False,True
8,False,False,True,False,False,False,True,True,False,False,True
9,False,False,True,False,False,False,False,False,True,False,False
10,True,False,False,True,True,True,False,False,False,False,False
11,True,False,False,True,True,True,False,False,False,False,False
12,False,True,False,False,True,False,False,False,False,True,False
13,False,False,True,True,True,False,False,False,False,False,False
14,True,False,True,False,False,False,False,False,False,True,False
15,False,False,False,False,True,True,False,False,False,True,False
16,False,True,True,False,False,False,False,False,False,True,False
17,False,False,True,False,True,False,False,False,False,True,False
18,False,False,True,False,True,False,False,False,False,True,False
19,False,False,False,False,True,True,False,False,True,False,True

In [20]:
len(list(filter(lambda qwe: qwe == True, df["BISCUIT"])))

7

In [21]:
len(df["BISCUIT"])

20

In [22]:
7/20

0.35

In [28]:
from mlxtend.frequent_patterns import apriori
df1 = apriori(df,min_support=0.01, use_colnames=True)
pd.set_option('display.max_rows', 500)
df1.sort_values(by="support",ascending=False)
def check_in_list(ruleitem, basketitem):  #helper checking function
#     print("basketitem=", basketitem)
#     print("ruleitem=",list(ruleitem))
    ret = all(t in list(ruleitem) for t in basketitem)
#     print(ret)
    return ret

def next_item(basketitems):
    if basketitems is None:
        return df1["itemsets"][0]
    max_len_apriori=len(basketitems) + 1
    df2 = apriori(df,min_support=0.01, max_len=max_len_apriori, use_colnames=True)  #list of only 1 items
    df2 = df2[df2["itemsets"].apply(len) > max_len_apriori-1]
    df2["check_in_list"] = df2["itemsets"].apply(check_in_list, args=(basketitems,))
    df2 = df2[df2["check_in_list"] == True]
    df2 = df2.sort_values(by="support",ascending=False)  #sort desc by support value
#     print(df2)
    if(len(df2) > 0):
        return list(df2["itemsets"])[0]

In [32]:
item=next_item(['BISCUIT'])
print(list(item))

NameError: name 'check_in_list' is not defined